### ISSUE TITLE
Clean Code: A Handbook Of Agile Software Craftsmanship chapter 11 to 13, 2023-01-07

### ISSUE THREAD

**Issue by jongfeel** [silqwer/book-club#18]
## 2022년 12월 23일 ~ 2023년 01월 06일(금)

10장 클래스 못한 부분 논의
11장 시스템
12장 창발성
13장 동시성
까지 읽고 아래와 같이 진행
- (Required) chapter 당 한 개 이상 논의 내용 작성, 총 3개 논의 내용 필요
- (Optional) 책 내용 정리 외에 추가 논의, 질문, 공유 정보 작성
- Reviewer는 자신을 제외한 멤버 모두 할당

## Before meeting

다른 멤버의 pull request review를 1일의 시간에 진행 해야 하며
pull request 당 적어도 1개 이상 코멘트 추가, 이후 approve를 통해 리뷰 했다는 걸 인증

## 2023년 01월 07일 토요일

홍대입구, 스타벅스 동교점에서 10시에 진행

**Comment by silqwer** [comment]
동시성 너무 많아여 ㅠㅠ, 이제 12장 시작 ㅠㅠ
